title: My thoughts about everything!!!!
email: your-email@domain.com
description: I am right. Read my every thought.
baseurl: "/second-best-blog-ever"
url: sashax.github.io
twitter_username: jekyllrb
github_username: sashax
markdown: kramdown
theme: default
